version: '3'

services:
  hdfs-edgenode:
    image: hshekhar47/hdfs-edgenode:0.1
    hostname: hdfs-edgenode
    stdin_open: true
    environment:
      - HADOOP_NAMENODE_HOSTNAME=hdfs-namenode
      - HIVE_SCHEMA_TYPE=mysql
      - HIVE_MYSQL_HOSTNAME=hive-metastore-db
      - HIVE_MYSQL_USER=hiveadmin
      - HIVE_MYSQL_PASSWORD=hiveadmin
    links:
      - hdfs-namenode
      - hive-metastore-db
      - db-external
    depends_on:
      - hdfs-namenode
      - hive-metastore-db
      - db-external
      
  hdfs-namenode:
    image: hshekhar47/hdfs-namenode:0.1
    hostname: hdfs-namenode
    stdin_open: true
    environment:
      - HADOOP_DATANODES=hdfs-datanode01 hdfs-datanode02
    ports:
      - "50070:50070"     # HDFS UI 
      - "19888:19888"     # Map Reduce Job History UI
      - "16010:16010"     # HBASE UI
      - "8088:8088"       # Yarn UI
      - "18080:18080"     # Spark Master UI       
      - "4040:4040"
    links:
      - hdfs-datanode01
      - hdfs-datanode02

  hdfs-datanode01:
    image: hshekhar47/hdfs-datanode:0.1
    hostname: hdfs-datanode01
    stdin_open: true
    environment:
      - HADOOP_NAMENODE_HOSTNAME=hdfs-namenode
    ports:
      - "50175:50075"
      - "8142:8042"
  
  hdfs-datanode02:
    image: hshekhar47/hdfs-datanode:0.1
    hostname: hdfs-datanode02
    stdin_open: true
    environment:
      - HADOOP_NAMENODE_HOSTNAME=hdfs-namenode
    ports:
      - "50275:50075"
      - "8242:8042"

  hive-metastore-db:
    image: hshekhar47/mysql:0.1
    hostname: hive-metastore-db
    stdin_open: true
    environment:
      - MYSQL_ROOT_PASSWORD=s3kr3t
      - MYSQL_USER=hiveadmin
      - MYSQL_PASSWORD=hiveadmin
      - MYSQL_DATABASE=hive_metastore_db
    ports:
      - "3307:3306"
  
  db-external:
    image: hshekhar47/mysql:0.1
    hostname: db-external
    stdin_open: true
    environment:
      - MYSQL_ROOT_PASSWORD=s3kr3t
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=dbadmin
      - MYSQL_DATABASE=sample
    ports:
      - "3306:3306"
    volumes:
      - /home/hshekhar/Projects/datasets:/share
